ComputeLiouvillian_0 – Charge Migration
ComputeLiouvillian_0 Subroutine
49 statements
Source File
subroutine ComputeLiouvillian_0(Evec, Dmat, Liouvillian0, bath_temperature, dephasing_factor, relaxation_factor)
Calculates the time-independent Lindblad superoperator (Liouvillian), a crucial element in the Lindblad master equation, used for describing the time evolution of the density matrix of a quantum system in an open quantum system framework.
Key steps in the subroutine: * First, the subroutine initializes parameters and allocates space for the Liouvillian. * The unitary part of the Liouvillian is computed, based on the system Hamiltonian eigenvalues. * The subroutine calculates the pair relaxation rates and the dephasing rates for all pairs of states, taking into account the energy levels, dipole moment matrix, and input parameters related to dephasing and relaxation. * The total relaxation rate for each state is computed as the sum of the pair relaxation rates involving the state. * Finally, the dissipative part of the Liouvillian, capturing the effects of the interaction of the system with its environment, is computed based on these relaxation rates.
Note: Please note that this subroutine computes the Lindblad superoperator for a specific case where the relaxation and dephasing rates are assumed to be constants and the Lindblad operators are assumed to be proportional to the dipole moment operator.
Arguments
Type Intent Optional Attributes Name
real(kind=kind(1d0)), intent(in) :: Evec(:)
The array of energy eigenvalues of the system's Hamiltonian.
real(kind=kind(1d0)), intent(in) :: Dmat(:,:,:)
The dipole moment matrix of the system.
complex(kind=kind(1d0)), intent(out), allocatable :: Liouvillian0(:,:)
The computed Liouvillian superoperator. It's an output parameter that's updated in the subroutine.
real(kind=kind(1d0)), intent(in) :: bath_temperature
The temperature of the bath or environment interacting with the quantum system.
real(kind=kind(1d0)), intent(in) :: dephasing_factor
The factor representing dephasing effects in the system.
real(kind=kind(1d0)), intent(in) :: relaxation_factor
The factor representing relaxation effects in the system.
Calls
Called by
Call graph
computeliouvillian_0 calls hilberttoliouvilleindexes, liouvilletohilbertindexes
chargemigration calls computeliouvillian_0