ComputeAtomicWeights – Charge Migration
ComputeAtomicWeights Subroutine
16 statements
Source File
subroutine ComputeAtomicWeights(nPts, gridv, nAtoms, AtCoord, WeightV, Radius_BS)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nPts
real(kind=kind(1d0)), intent(in) :: gridv(:,:)
integer, intent(in) :: nAtoms
real(kind=kind(1d0)), intent(in) :: AtCoord(:,:)
real(kind=kind(1d0)), intent(out), allocatable :: WeightV(:,:)
real(kind=kind(1d0)), intent(in) :: Radius_BS(:)
Calls
Called by
Call graph
computeatomicweights calls wkfun
wkfun calls pkfuna, pkfuntot
pkfuna calls get_param_a, skfunab
pkfuntot calls pkfuna
skfunab calls ellipticalcoord, new_mu_transformation, skfun
ellipticalcoord calls eucldist
skfun calls fkfun
fkfun calls fkfun
chargemigration calls computeatomicweights