GetRunTimeParameters – Charge Migration
GetRunTimeParameters Subroutine
89 statements
Source File
public subroutine GetRunTimeParameters(input_directory, output_directory, molecular_geometry_file, n_times, t_min, t_max, FieldFile, Verbous, Weight_File, read_precomputed_weights_flag, save_charge_migration_flag, ivorb, counted_number_of_orbitals, dephasing_factor, relaxation_factor, bath_temperature)
Uses
ModuleErrorHandling
ModuleString
ModuleCommandLineParameterList
Reads the run time parameters specified in the command line. Reads the run time parameters specified in the command line.
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(out), allocatable :: input_directory
character(len=:), intent(out), allocatable :: output_directory
character(len=:), intent(out), allocatable :: molecular_geometry_file
integer, intent(out) :: n_times
real(kind=kind(1d0)), intent(out) :: t_min
real(kind=kind(1d0)), intent(out) :: t_max
character(len=:), intent(out), allocatable :: FieldFile
logical, intent(out) :: Verbous
character(len=:), intent(out), allocatable :: Weight_File
logical, intent(out) :: read_precomputed_weights_flag
logical, intent(out) :: save_charge_migration_flag
integer, intent(out), allocatable :: ivorb(:)
integer, intent(out) :: counted_number_of_orbitals
real(kind=kind(1d0)), intent(out) :: dephasing_factor
real(kind=kind(1d0)), intent(out) :: relaxation_factor
real(kind=kind(1d0)), intent(out) :: bath_temperature
Calls
Called by
Call graph
getruntimeparameters calls add, get, parse, printusage, setdescription
chargemigration calls getruntimeparameters