GetRunTimeParameters – Charge Migration
GetRunTimeParameters Subroutine
61 statements
Source File
public subroutine GetRunTimeParameters(InpDir, OutDir, FileGeometry, StepTime, StepWidth, FieldFile, Verbous, nOmegas, OmegaMin, OmegaMax, nTauOmegas, TauOmegaMin, TauOmegaMax)
Uses
ModuleErrorHandling
ModuleString
ModuleCommandLineParameterList
Reads the run time parameters specified in the command line.
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(out), allocatable :: InpDir
character(len=:), intent(out), allocatable :: OutDir
character(len=:), intent(out), allocatable :: FileGeometry
real(kind=kind(1d0)), intent(out) :: StepTime
real(kind=kind(1d0)), intent(out) :: StepWidth
character(len=:), intent(out), allocatable :: FieldFile
logical, intent(out) :: Verbous
integer, intent(out) :: nOmegas
real(kind=kind(1d0)), intent(out) :: OmegaMin
real(kind=kind(1d0)), intent(out) :: OmegaMax
integer, intent(out) :: nTauOmegas
real(kind=kind(1d0)), intent(out) :: TauOmegaMin
real(kind=kind(1d0)), intent(out) :: TauOmegaMax
Calls
Called by
Call graph
getruntimeparameters calls add, get, parse, printusage, setdescription
chargemigrationft calls getruntimeparameters