HilbertToLiouvilleIndexes – Charge Migration
HilbertToLiouvilleIndexes Subroutine
11 statements
Source File
subroutine HilbertToLiouvilleIndexes(i, j, iPair)
Transforms matrix indices in Hilbert space into a single index in Liouville space. The transformation is dependent on the relative values of the input indices. The resulting single index is required for the transformation from Hilbert to Liouville space.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
Integers representing the indices in Hilbert space.
integer, intent(in) :: j
Integers representing the indices in Hilbert space.
integer, intent(out) :: iPair
An integer representing the corresponding single index in Liouville space.
Called by
Call graph
computeliouvillian_0 calls hilberttoliouvilleindexes
hilberttoliouvillematrix calls hilberttoliouvilleindexes
liouvilletohilbertmatrix calls hilberttoliouvilleindexes
liouvillianpropagator calls hilberttoliouvillematrix, liouvilletohilbertmatrix
chargemigration calls computeliouvillian_0, liouvillianpropagator