PkFunTot – Charge Migration
PkFunTot Function
10 statements
Source File
public function PkFunTot(rvec, AtCoord, nAtoms, k, Radius_BS) result(res)
Eq. 3 in the denominator This function calculates the total partition function. This is done by summing the partial partition functions for all atoms.
Arguments
Type Intent Optional Attributes Name
real(kind=kind(1d0)), intent(in) :: rvec(3)
real(kind=kind(1d0)), intent(in) :: AtCoord(3,nAtoms)
integer, intent(in) :: nAtoms
integer, intent(in) :: k
real(kind=kind(1d0)), intent(in) :: Radius_BS(:)
Return Value real(kind=kind(1d0))
Calls
Called by
Call graph
pkfuntot calls pkfuna
pkfuna calls get_param_a, skfunab
skfunab calls ellipticalcoord, new_mu_transformation, skfun
ellipticalcoord calls eucldist
skfun calls fkfun
fkfun calls fkfun
wkfun calls pkfuntot
computeatomicweights calls wkfun
chargemigration calls computeatomicweights