wkfun – Charge Migration
wkfun Function
5 statements
Source File
public function wkfun(rvec, iAtom, AtCoord, nAtoms, k, Radius_BS) result(res)
Eq. 3 $w_a \vec(r)$ (WEIGHTS) This function calculates the weight of an atom. The weight is defined as the ratio of the partial partition function of the atom to the total partition function. This weight represents the relative importance of the atom.
Arguments
Type Intent Optional Attributes Name
real(kind=kind(1d0)), intent(in) :: rvec(3)
integer, intent(in) :: iAtom
real(kind=kind(1d0)), intent(in) :: AtCoord(3,nAtoms)
integer, intent(in) :: nAtoms
integer, intent(in) :: k
real(kind=kind(1d0)), intent(in) :: Radius_BS(:)
Return Value real(kind=kind(1d0))
Calls
Called by
Call graph
wkfun calls pkfuna, pkfuntot
pkfuna calls get_param_a, skfunab
pkfuntot calls pkfuna
skfunab calls ellipticalcoord, new_mu_transformation, skfun
ellipticalcoord calls eucldist
skfun calls fkfun
fkfun calls fkfun
computeatomicweights calls wkfun
chargemigration calls computeatomicweights