#CONFIDENTIAL
ALL_PRGS = astraBuildOperator          \
           astraConvertIntegralsUKRmol \
           astraConvertDensityMatrices \
           astraSetup                  \
           astraTest                   \
           TestIntegralsFullFullMatrix \
           astraBuildSTEX_TDMs         \
           TestBlocks
           #astraCondition              \
           #ChargeMigration             \
           #testBS_FEDVR                \
	   #Split3DGrid                 \
           #TestIntegralsFullFullMatrix \
           #testModuleMatrix
           #ChargeMigrationFT           \
           #TemplateProgram             \
           #ChargeMigration             \
           #ChargeMigrationFT           \
           #testBS_FEDVR                \
	   #Split3DGrid
           #TestAngularMomentum         \
           #tmp_LocLocMatrix            \
           #tmp_FullFullMatrix          \
           #TestBsplines_Juan           \
           #ComputeSpectrum_H0_CCO      \
           #ComputeScatteringStates

include etc/CompilerOptions.mk
