#CONFIDENTIAL
ALL_PRGS = astraBuildOperator          \
           astraConvertIntegralsUKRmol \
           astraConvertDensityMatrices \
           astraSetup                  \
           astraCondition              \
           astraTest                   \
           ChargeMigration             \
           testBS_FEDVR                \
           TestIntegralsFullFullMatrix \
           ChargeMigrationFT		\
           SpectrumReconstruction           
           #TestIntegralsFullFullMatrix
           #TemplateProgram             \
           #testBS_FEDVR                \
           #astraBuildSTEX_TDMs
           #TestAngularMomentum         \
           #tmp_LocLocMatrix            \
           #tmp_FullFullMatrix          \
           #TestBsplines_Juan           \
           #ComputeSpectrum_H0_CCO      \
           #ComputeScatteringStates

include etc/CompilerOptions.mk
