! CONFIDENTIAL
!! Copyright (C) 2020 Luca Argenti, PhD - All Rights Reserved
!! email: luca.argenti@gmail.com
!! email: luca.argenti@ucf.edu
!! Luca Argenti is Associate Professor of Physics, Optics and Photonics
!! at the Department of Physics and the College of Optics
!! of the University of Central Florida
!! 4111 Libra Drive
!! Orlando, Florida, USA
!!
!>  Insert Doxygen comments here
!!  
!!  This program builds an "arbitray" operator between
!!  symmetric close-coupling spaces of a molecule, within
!!  D2h and its subgroups.
!! 
program ConvertIntegralsUKRmol

  use, intrinsic :: ISO_FORTRAN_ENV

  use ModuleUKRmolInterface

  use ModuleString
  use ModuleGroups
  use ModuleAstraConfigFile
  use ModuleOrbitalBasis
  use ModuleXlm
  use ModuleIntegrals
  use ModuleESpace

  use ModuleMainInterface

  implicit none

  !.. Run time parameters
  character(len=:), allocatable :: AstraConfigFile

  !.. Config file parameters
  character(len=:), allocatable :: StorageDir
  character(len=:), allocatable :: QCDir
  character(len=:), allocatable :: ccConfigFile
  character(len=:), allocatable :: MoldenFile
  character(len=:), allocatable :: IntegralFile

  type(ClassESpace)             :: Space
  type(ClassGroup), pointer     :: Group
  integer                       :: lmax

  call GetRunTimeParameters( AstraConfigFile )

  call ParseAstraConfigFile( &
       AstraConfigFile     , &
       ccConfigFile        , &
       StorageDir          , &
       QCDir               , &
       MoldenFile          , &
       IntegralFile        )
  
  call Space%SetRootDir     ( StorageDir   )
  call Space%ParseConfigFile( ccConfigFile )

  Group => Space%GetGroup()
  lmax  =  Space%GetLmax()

  call GlobalGroup%Init(Group%GetName())
  call GlobalXlmSet%Init(Group,2*lmax)

  call UKRmol_Orbitals%Init(QCDir//"/"//IntegralFile)
  call UKRMol_Init_Integrals(QCDir,QCDir//"/"//MoldenFile,QCDir//"/"//IntegralFile)

  call GlobalIntegral%SetStorage( AddSlash(StorageDir) )
  call GlobalIntegral%WriteToFile()

  call OrbitalBasis%SetStorageDir(StorageDir)
  call OrbitalBasis%Save()

  !.. Remove/relocate unnecessary output generated by the libGBTO interface
  call Execute_Command_line("rm -f fort.10 fort.3")
  call Execute_Command_line("mkdir -p      "//StorageDir//"/log/")
  call Execute_Command_line("mv log_file.0 "//StorageDir//"/log/")
  
  stop

end program ConvertIntegralsUKRmol
