ChargeMigrationFT – Charge Migration
ChargeMigrationFT Program
296 statements
Source File
Uses
iso_fortran_env
ModuleDiagonalize
ModuleConstants
Module_CMFT_RTP
ModulePulses_3D
ModuleErrorHandling
ModuleSystemUtils
ModuleString
Module_CMFT_CD_IO
ModuleIO
Calls
Variables
Type Attributes Name Initial
character(len=:), allocatable :: InpDir
character(len=:), allocatable :: OutDir
character(len=:), allocatable :: FileGeometry
real(kind=kind(1d0)) :: StepTime
real(kind=kind(1d0)) :: StepWidth
character(len=:), allocatable :: Ext_field_file
logical :: Verbous
integer :: nOmegas
integer :: nTauOmegas
real(kind=kind(1d0)) :: OmegaMin
real(kind=kind(1d0)) :: OmegaMax
real(kind=kind(1d0)) :: TauOmegaMin
real(kind=kind(1d0)) :: TauOmegaMax
complex(kind=kind(1d0)), allocatable :: DipoleFTtotal(:,:)
complex(kind=kind(1d0)), allocatable :: DipoleFTminus(:,:)
complex(kind=kind(1d0)), allocatable :: DipoleFTplus(:,:)
complex(kind=kind(1d0)), allocatable :: DipoleFTwt(:,:,:)
complex(kind=kind(1d0)), allocatable :: DipoleFTww(:,:,:)
complex(kind=kind(1d0)), allocatable :: AtomicChargeFT(:,:,:)
complex(kind=kind(1d0)), allocatable :: ChargeFTwt(:,:,:,:)
complex(kind=kind(1d0)), allocatable :: ChargeFTww(:,:,:,:)
complex(kind=kind(1d0)), allocatable :: XUVCharge(:,:,:)
real(kind=kind(1d0)), allocatable :: OmegaVec(:)
real(kind=kind(1d0)), allocatable :: TauOmegaVec(:)
real(kind=kind(1d0)), allocatable :: tvec(:)
integer :: iOmega
integer :: ntimes
integer :: i
real(kind=kind(1d0)) :: tmin
real(kind=kind(1d0)) :: tmax
character(len=*), parameter :: DIPOLE_FT_PATH_ALL = "/Dipole/DipoleFT_ALL.csv"
character(len=*), parameter :: CHARGE_FT_PATH_ALL = "/AtomicCharge/AtomicChargeFT_ALL.csv"
integer, parameter :: GS_IDX = 1
integer :: nStates
integer :: uid_AtomicChargeALL
integer :: uid
real(kind=kind(1d0)), allocatable :: Evec(:)
complex(kind=kind(1d0)), allocatable :: zMuEV(:,:)
integer :: nAtoms
real(kind=kind(1d0)), allocatable :: AtCoord(:,:)
character(len=16), allocatable :: AtomName(:)
real(kind=kind(1d0)) :: dt
integer :: iSim
integer :: N_Simulations
character(len=64), pointer :: Simulation_Tagv(:)
type(pulse_train), pointer :: train(:)
complex(kind=kind(1d0)), allocatable :: XUVDipole(:,:)
complex(kind=kind(1d0)), allocatable :: XUVDipoleFT(:,:)
real(kind=kind(1d0)), allocatable :: AtomicChargeEvolution(:,:,:)
complex(kind=kind(1d0)), allocatable :: Debug(:,:,:)
integer :: iPol
integer :: iAtom
integer :: it
integer :: iCoord
Subroutines
subroutine DetermineNumberOfTimes(FileName, tmin, tmax, nTimes)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: FileName
real(kind=kind(1d0)), intent(out) :: tmin
real(kind=kind(1d0)), intent(out) :: tmax
integer, intent(out) :: nTimes
subroutine Regularize_XUVDipole(XUVDipole, tmin, dt, nTimes, StepTime, StepWidth)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(inout) :: XUVDipole(:,:)
real(kind=kind(1d0)), intent(in) :: tmin
real(kind=kind(1d0)), intent(in) :: dt
integer, intent(in) :: nTimes
real(kind=kind(1d0)), intent(in) :: StepTime
real(kind=kind(1d0)), intent(in) :: StepWidth
subroutine Regularize_XUVAtomicCharge(Charge, tmin, dt, nTimes, StepTime, StepWidth)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(inout) :: Charge(:,:,:)
real(kind=kind(1d0)), intent(in) :: tmin
real(kind=kind(1d0)), intent(in) :: dt
integer, intent(in) :: nTimes
real(kind=kind(1d0)), intent(in) :: StepTime
real(kind=kind(1d0)), intent(in) :: StepWidth
subroutine Regularize_Dipole_and_AtomicCharge1(Dipole, Charge, tmin, dt, nTimes, StepTime, StepWidth)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(inout) :: Dipole(:,:)
real(kind=kind(1d0)), intent(inout) :: Charge(:,:,:)
real(kind=kind(1d0)), intent(in) :: tmin
real(kind=kind(1d0)), intent(in) :: dt
integer, intent(in) :: nTimes
real(kind=kind(1d0)), intent(in) :: StepTime
real(kind=kind(1d0)), intent(in) :: StepWidth
subroutine ComputeFT_Dipole_and_AtomicCharges(DipoleFTminus, AtomicChargeFT, Dipole, OmegaVec, AtomicChargeEvolution, tmin, dt, nTimes, nOmegas)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(out) :: DipoleFTminus(:,:)
complex(kind=kind(1d0)), intent(out), allocatable :: AtomicChargeFT(:,:,:)
complex(kind=kind(1d0)), intent(in) :: Dipole(:,:)
real(kind=kind(1d0)), intent(in) :: OmegaVec(:)
real(kind=kind(1d0)), intent(in) :: AtomicChargeEvolution(:,:,:)
real(kind=kind(1d0)), intent(in) :: tmin
real(kind=kind(1d0)), intent(in) :: dt
integer, intent(in) :: nTimes
integer, intent(in) :: nOmegas
subroutine Regularize_Dipole_withRespectto_TimeDelay(DipoleFTwt, tvec, N_Simulations)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(inout) :: DipoleFTwt(:,:,:)
real(kind=kind(1d0)), intent(in) :: tvec(:)
integer, intent(in) :: N_Simulations
subroutine Compute_FTofDipole_withRespectto_Time(DipoleFTwt, DipoleFTww, tvec, TauOmegaVec, N_Simulations, nTauOmegas)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(in) :: DipoleFTwt(:,:,:)
complex(kind=kind(1d0)), intent(out), allocatable :: DipoleFTww(:,:,:)
real(kind=kind(1d0)), intent(in) :: tvec(:)
real(kind=kind(1d0)), intent(in) :: TauOmegaVec(:)
integer, intent(in) :: N_Simulations
integer, intent(in) :: nTauOmegas
subroutine Regularize_Charge_withtimedelay(ChargeFTwt, tvec, nAtoms, N_Simulations)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(inout) :: ChargeFTwt(:,:,:,:)
real(kind=kind(1d0)), intent(in) :: tvec(:)
integer, intent(in) :: nAtoms
integer, intent(in) :: N_Simulations
subroutine Compute_FTCharge_withTimeDelay(ChargeFTwt, tvec, ChargeFTww, N_simulations, nOmegas, nAtoms, nTauOmegas, TauOmegaVec)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(in) :: ChargeFTwt(:,:,:,:)
real(kind=kind(1d0)), intent(in) :: tvec(:)
complex(kind=kind(1d0)), intent(out), allocatable :: ChargeFTww(:,:,:,:)
integer, intent(in) :: N_simulations
integer, intent(in) :: nOmegas
integer, intent(in) :: nAtoms
integer, intent(in) :: nTauOmegas
real(kind=kind(1d0)), intent(in) :: TauOmegaVec(:)
Call graph
chargemigrationft calls parse_simulation_file, appenddipole2ftallfile, compute_ftcharge_withtimedelay, compute_ftofdipole_withrespectto_time, computeft_dipole_and_atomiccharges, determinenumberoftimes, getruntimeparameters, load_dipole, load_q_charge_and_write2all, load_xuvatomiccharge, loadenergies, loadftdipole_asfuncitonof_timedelay, loadftofchargeasfuncoftimedelay, loadgeometry, regularize_charge_withtimedelay, regularize_dipole_and_atomiccharge1, regularize_dipole_withrespectto_timedelay, regularize_xuvatomiccharge, regularize_xuvdipole, savebidimentioal_dipole_spectrum, set_cd_io_verbous, write_bidimentionalchargeftww, writeallatomicchargefttosinglefile, writeatomicchargeft, writedipoleftfile
appenddipole2ftallfile calls p
getruntimeparameters calls add, get, parse, printusage, setdescription
loadenergies calls errormessage
regularize_charge_withtimedelay calls ncd_phi
regularize_dipole_and_atomiccharge1 calls ncd_phi
regularize_dipole_withrespectto_timedelay calls ncd_phi
regularize_xuvatomiccharge calls ncd_phi
regularize_xuvdipole calls ncd_phi
writeallatomicchargefttosinglefile calls p