ChargeMigration – Charge Migration
ChargeMigration Program
567 statements
Source File
Uses
ModuleSystemUtils
ModuleIO
omp_lib
Module_CM_CD_IO
ModuleString
Module_CM_RTP
Module_Becke
ModuleErrorHandling
ModulePulses_3D
ModuleDiagonalize
ModuleConstants
iso_fortran_env
Synopsis: Simulates charge migration in molecular systems under external fields, relaxations, and dephasing effects using the Lindblad master equation.
Key Subroutines:
LiouvillianPropagator: This central routine simulates the dynamics of a quantum system subject to an external field. It updates the state density matrix zStatRho using the eigenvalues L0_Eval and eigenvectors L0_LEvec, L0_REvec of the Liouvillian operator.
ComputeLiouvillian_0: Calculates the time-independent Lindblad superoperator (Liouvillian), crucial in describing the time evolution of the density matrix in an open quantum system. It uses system energy eigenvalues Evec, dipole moment matrix Dmat, and parameters like bath_temperature, dephasing_factor, and relaxation_factor.
DiagonalizeLindblad_0: Performs diagonalization of the Lindblad superoperator Liouvillian0, determining its eigenvalues L0_Eval and eigenvectors L0_LEvec and L0_REvec.
HilbertToLiouvilleMatrix and LiouvilleToHilbertMatrix: These subroutines transform between Hilbert space matrices and Liouville space vectors. They are crucial for applying the Liouville operator in the simulations.
ComputeOrbitalDensity: Builds the orbital density matrix Amat from the state density matrix zStatRho and transition density matrices TDM.
ComputeAtomicCharges: Calculates new atomic charges QchargeVec from the orbital density OrbitalDensity and Becke matrix BeckeMatrix.
TabulateChargeDensity: Generates charge density ChDen from the orbital density matrix Amat and orbital table OrbTab.
ComputeBeckeMatrix: Constructs the Becke matrix BeckeMatrix using weights WeightV, orbital table OrbTab, and barycenter coordinates Bary_center.
ComputeAtomicWeights: Calculates atomic weights WeightV for a given set of points gridv, atomic coordinates AtCoord, and radii Radius_BS.
Calls
Variables
Type Attributes Name Initial
character(len=:), allocatable :: input_directory
character(len=:), allocatable :: output_directory
character(len=:), allocatable :: molecular_geometry_file
integer :: n_times
real(kind=kind(1d0)) :: t_min
real(kind=kind(1d0)) :: t_max
character(len=:), allocatable :: Ext_field_file
character(len=:), allocatable :: Weight_File
logical :: Verbous
logical :: read_precomputed_weights_flag
logical :: save_charge_migration_flag
integer, allocatable :: ivorb(:)
integer :: counted_number_of_orbitals
real(kind=kind(1d0)) :: dephasing_factor
real(kind=kind(1d0)) :: relaxation_factor
real(kind=kind(1d0)) :: bath_temperature
integer, parameter :: GS_IDX = 1
integer :: nStates
integer :: number_of_orbitals
integer :: i
real(kind=kind(1d0)), allocatable :: Evec(:)
real(kind=kind(1d0)), allocatable :: Dmat(:,:,:)
real(kind=kind(1d0)), allocatable :: TDM(:,:,:,:)
complex(kind=kind(1d0)), allocatable :: zMuEV(:,:)
complex(kind=kind(1d0)), allocatable :: zDmat_t(:,:,:)
integer :: npts
integer :: nAtoms
real(kind=kind(1d0)), allocatable :: gridv(:,:)
real(kind=kind(1d0)), allocatable :: AtCoord(:,:)
real(kind=kind(1d0)), allocatable :: OrbTab(:,:)
complex(kind=kind(1d0)), allocatable :: zStatRho(:,:)
real(kind=kind(1d0)) :: t
real(kind=kind(1d0)) :: dt
real(kind=kind(1d0)), allocatable :: ChDen(:)
real(kind=kind(1d0)), allocatable :: WEIGHTV(:,:)
real(kind=kind(1d0)), allocatable :: AtomicChargeVec(:,:)
real(kind=kind(1d0)), allocatable :: AtomicChargeEvolution(:,:,:)
character(len=30) :: istrn
character(len=16), allocatable :: atom_names(:)
integer :: iPts
integer :: it
integer :: iPol
integer :: iAtom
complex(kind=kind(1d0)), allocatable :: Liouvillian0(:,:)
complex(kind=kind(1d0)), allocatable :: L0_LEvec(:,:)
complex(kind=kind(1d0)), allocatable :: L0_REvec(:,:)
complex(kind=kind(1d0)), allocatable :: L0_Eval(:)
integer :: iSim
integer :: N_Simulations
integer :: uid
character(len=64), pointer :: Simulation_Tagv(:)
character(len=1000) :: strn
type(pulse_train), pointer :: train(:)
real(kind=kind(1d0)), allocatable :: BeckeMatrix(:,:,:,:)
real(kind=kind(1d0)), allocatable :: OrbitalDensity(:,:)
real(kind=kind(1d0)), allocatable :: Radius_BS(:)
real(kind=kind(1d0)) :: Computed_volume
integer :: iOrb
integer :: jOrb
real(kind=kind(1d0)), allocatable :: QchargeVec(:,:)
real(kind=kind(1d0)), allocatable :: R_el(:,:)
Functions
function zTraceFunction(zA) result(zTrace)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(in) :: zA(:,:)
Return Value complex(kind=kind(1d0))
Subroutines
subroutine LiouvillianPropagator(L0_Eval, L0_LEvec, L0_REvec, zStatRho)
The central routine in simulating the dynamics of a quantum system subject to an external field, describing the time evolution of the system in Liouville space. Build the time-independent Lindblad superoperator
Read more…
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(in) :: L0_Eval(:)
a complex array holding the eigenvalues of the Liouville operator.
complex(kind=kind(1d0)), intent(in) :: L0_LEvec(:,:)
a complex array holding the left eigenvectors of the Liouville operator.
complex(kind=kind(1d0)), intent(in) :: L0_REvec(:,:)
a complex array holding the right eigenvectors of the Liouville operator.
complex(kind=kind(1d0)), intent(inout) :: zStatRho(:,:)
a complex array holding the initial state density matrix of the quantum system. The array is updated within the subroutine, and hence is an input/output parameter.
subroutine ComputeLiouvillian_0(Evec, Dmat, Liouvillian0, bath_temperature, dephasing_factor, relaxation_factor)
Calculates the time-independent Lindblad superoperator (Liouvillian), a crucial element in the Lindblad master equation, used for describing the time evolution of the density matrix of a quantum system in an open quantum system framework.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=kind(1d0)), intent(in) :: Evec(:)
The array of energy eigenvalues of the system's Hamiltonian.
real(kind=kind(1d0)), intent(in) :: Dmat(:,:,:)
The dipole moment matrix of the system.
complex(kind=kind(1d0)), intent(out), allocatable :: Liouvillian0(:,:)
The computed Liouvillian superoperator. It's an output parameter that's updated in the subroutine.
real(kind=kind(1d0)), intent(in) :: bath_temperature
The temperature of the bath or environment interacting with the quantum system.
real(kind=kind(1d0)), intent(in) :: dephasing_factor
The factor representing dephasing effects in the system.
real(kind=kind(1d0)), intent(in) :: relaxation_factor
The factor representing relaxation effects in the system.
subroutine DiagonalizeLindblad_0(Liouvillian0, L0_Eval, L0_LEvec, L0_REvec)
Performs the diagonalization of the time-independent Lindblad superoperator (Liouvillian0). The diagonalization is performed using the Short_Diag subroutine, and the results are printed to the standard output. This routine also checks that the product of right and conjugate transpose of left eigenvectors is an identity matrix (a necessary condition for a valid diagonalization).
Read more…
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(inout) :: Liouvillian0(:,:)
A complex square matrix representing the Lindblad superoperator to be diagonalized.
complex(kind=kind(1d0)), intent(out), allocatable :: L0_Eval(:)
A complex vector that will hold the eigenvalues of Liouvillian0.
complex(kind=kind(1d0)), intent(out), allocatable :: L0_LEvec(:,:)
A complex square matrix that will hold the left eigenvectors of Liouvillian0.
complex(kind=kind(1d0)), intent(out), allocatable :: L0_REvec(:,:)
A complex square matrix that will hold the right eigenvectors of Liouvillian0.
subroutine HilbertToLiouvilleMatrix(RhoMat, RhoVec)
Transforms a matrix from Hilbert space into a vector in Liouville space. The transformation is performed by looping through each element of the input matrix and mapping it to the corresponding position in the output vector using the subroutine HilbertToLiouvilleIndexes. This transformation is required for the application of the Liouville operator.
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(in) :: RhoMat(:,:)
A complex matrix representing the state in Hilbert space.
complex(kind=kind(1d0)), intent(out) :: RhoVec(:)
A complex vector representing the transformed state in Liouville space.
subroutine LiouvilleToHilbertMatrix(RhoVec, RhoMat)
Performs the inverse transformation of HilbertToLiouvilleMatrix, transforming a vector in Liouville space back into a matrix in Hilbert space. The transformation is performed by looping through each element of the output matrix and assigning it the corresponding value from the input vector using the subroutine HilbertToLiouvilleIndexes.
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(in) :: RhoVec(:)
A complex vector representing the state in Liouville space.
complex(kind=kind(1d0)), intent(out) :: RhoMat(:,:)
A complex matrix representing the transformed state in Hilbert space.
subroutine HilbertToLiouvilleIndexes(i, j, iPair)
Transforms matrix indices in Hilbert space into a single index in Liouville space. The transformation is dependent on the relative values of the input indices. The resulting single index is required for the transformation from Hilbert to Liouville space.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
Integers representing the indices in Hilbert space.
integer, intent(in) :: j
Integers representing the indices in Hilbert space.
integer, intent(out) :: iPair
An integer representing the corresponding single index in Liouville space.
subroutine LiouvilleToHilbertIndexes(iPair, i, j)
Takes in a single integer index in Liouville space and converts it into a pair of matrix indices in Hilbert space. The indices are calculated by decomposing the given Liouville index into a square plus a remainder, which are then used to calculate the corresponding Hilbert indices.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iPair
An integer representing a single index in Liouville space.
integer, intent(out) :: i
Integers representing the corresponding indices in Hilbert space.
integer, intent(out) :: j
Integers representing the corresponding indices in Hilbert space.
subroutine DiagonalizeDipole(Dmat, EVEC_DX, zUMAT_DX, EVEC_DY, zUMAT_DY, EVEC_DZ, zUMAT_DZ)
input and computes the diagonalized matrices and their eigenvalues.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=kind(1d0)), intent(in) :: Dmat(:,:,:)
Real 3D array representing the dipole moment matrix.
real(kind=kind(1d0)), intent(out), allocatable :: EVEC_DX(:)
Real 1D arrays for the eigenvalues of the dipoles in X, Y, and Z directions.
complex(kind=kind(1d0)), intent(out), allocatable :: zUMAT_DX(:,:)
Complex 2D arrays for the diagonalized matrices in X, Y, and Z directions, respectively.
real(kind=kind(1d0)), intent(out), allocatable :: EVEC_DY(:)
Real 1D arrays for the eigenvalues of the dipoles in X, Y, and Z directions.
complex(kind=kind(1d0)), intent(out), allocatable :: zUMAT_DY(:,:)
Complex 2D arrays for the diagonalized matrices in X, Y, and Z directions, respectively.
real(kind=kind(1d0)), intent(out), allocatable :: EVEC_DZ(:)
Real 1D arrays for the eigenvalues of the dipoles in X, Y, and Z directions.
complex(kind=kind(1d0)), intent(out), allocatable :: zUMAT_DZ(:,:)
Complex 2D arrays for the diagonalized matrices in X, Y, and Z directions, respectively.
subroutine Computevolume(nPts, volume, gridv)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nPts
real(kind=kind(1d0)), intent(out) :: volume
real(kind=kind(1d0)), intent(in), allocatable :: gridv(:,:)
subroutine Compute_R_el(gridv, WeightV, OrbTab, R_el)
Arguments
Type Intent Optional Attributes Name
real(kind=kind(1d0)), intent(in), allocatable :: gridv(:,:)
real(kind=kind(1d0)), intent(in), allocatable :: WeightV(:,:)
real(kind=kind(1d0)), intent(in), allocatable :: OrbTab(:,:)
real(kind=kind(1d0)), intent(out), allocatable :: R_el(:,:)
subroutine AtomicRadius_Bragg_Slater_Becke(atom_names, nAtom, Radius_BS)
Arguments
Type Intent Optional Attributes Name
character(len=16), intent(in) :: atom_names(:)
integer, intent(in) :: nAtom
real(kind=kind(1d0)), intent(out), allocatable :: Radius_BS(:)
subroutine ComputeAtomicCharges(OrbitalDensity, BeckeMatrix, QchargeVec)
Arguments
Type Intent Optional Attributes Name
real(kind=kind(1d0)), intent(in) :: OrbitalDensity(:,:)
real(kind=kind(1d0)), intent(in) :: BeckeMatrix(:,:,:,:)
real(kind=kind(1d0)), intent(out), allocatable :: QchargeVec(:,:)
subroutine ComputeOrbitalDensity(zStatRho, TDM, Amat)
Build the expansion Matrix where is the solution of a suitable Master equation, starting from Here, we will neglect relaxation and decoherence and hence where
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(in) :: zStatRho(:,:)
real(kind=kind(1d0)), intent(in) :: TDM(:,:,:,:)
real(kind=kind(1d0)), intent(out), allocatable :: Amat(:,:)
subroutine ComputeAtomicWeights(nPts, gridv, nAtoms, AtCoord, WeightV, Radius_BS)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nPts
real(kind=kind(1d0)), intent(in) :: gridv(:,:)
integer, intent(in) :: nAtoms
real(kind=kind(1d0)), intent(in) :: AtCoord(:,:)
real(kind=kind(1d0)), intent(out), allocatable :: WeightV(:,:)
real(kind=kind(1d0)), intent(in) :: Radius_BS(:)
subroutine TabulateChargeDensity(Amat, OrbTab, ChDen)
Arguments
Type Intent Optional Attributes Name
real(kind=kind(1d0)), intent(in) :: Amat(:,:)
real(kind=kind(1d0)), intent(in) :: OrbTab(:,:)
real(kind=kind(1d0)), intent(out) :: ChDen(:)
subroutine ComputeBeckeMatrix(WeightV, OrbTab, BeckeMatrix, Bary_center)
Arguments
Type Intent Optional Attributes Name
real(kind=kind(1d0)), intent(in) :: WeightV(:,:)
real(kind=kind(1d0)), intent(in) :: OrbTab(:,:)
real(kind=kind(1d0)), intent(out), allocatable :: BeckeMatrix(:,:,:,:)
real(kind=kind(1d0)), intent(in) :: Bary_center(:,:)
Call graph
chargemigration calls omp_set_num_threads, parse_simulation_file, atomicradius_bragg_slater_becke, compute_r_el, computeatomiccharges, computeatomicweights, computebeckematrix, computeliouvillian_0, computeorbitaldensity, computevolume, diagonalizelindblad_0, getruntimeparameters, liouvillianpropagator, loaddipoleme, loadenergies, loadgeometry, loadgrid, loadorbitals, loadtdms, read_weights, set_cd_io_verbous, tabulatechargedensity, write_charge_density, write_dipole, write_q_charge, write_r_el_bc, write_summary, write_weights, writefta, zdotu
atomicradius_bragg_slater_becke calls radius_table
computeatomicweights calls wkfun
computeliouvillian_0 calls hilberttoliouvilleindexes, liouvilletohilbertindexes
diagonalizelindblad_0 calls short_diag, zgemm
getruntimeparameters calls add, get, parse, printusage, setdescription
liouvillianpropagator calls externalelectricfieldcart, diagonalizedipole, hilberttoliouvillematrix, liouvilletohilbertmatrix, short_zheev, zgemm, zgemv
loaddipoleme calls errormessage
loadenergies calls errormessage
loadgrid calls errormessage
loadorbitals calls assert, converttostrn, errormessage, stopexecution
loadtdms calls errormessage
write_charge_density calls errormessage
write_summary calls assert
diagonalizedipole calls short_diag
hilberttoliouvillematrix calls hilberttoliouvilleindexes
liouvilletohilbertmatrix calls hilberttoliouvilleindexes
wkfun calls pkfuna, pkfuntot
pkfuna calls get_param_a, skfunab
pkfuntot calls pkfuna
skfunab calls ellipticalcoord, new_mu_transformation, skfun
ellipticalcoord calls eucldist
skfun calls fkfun
fkfun calls fkfun