DiagonalizeLindblad_0 – Charge Migration
DiagonalizeLindblad_0 Subroutine
27 statements
Source File
subroutine DiagonalizeLindblad_0(Liouvillian0, L0_Eval, L0_LEvec, L0_REvec)
Performs the diagonalization of the time-independent Lindblad superoperator (Liouvillian0). The diagonalization is performed using the Short_Diag subroutine, and the results are printed to the standard output. This routine also checks that the product of right and conjugate transpose of left eigenvectors is an identity matrix (a necessary condition for a valid diagonalization).
Note: The input matrix Liouvillian0 is also modified during the execution of this subroutine.
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(inout) :: Liouvillian0(:,:)
A complex square matrix representing the Lindblad superoperator to be diagonalized.
complex(kind=kind(1d0)), intent(out), allocatable :: L0_Eval(:)
A complex vector that will hold the eigenvalues of Liouvillian0.
complex(kind=kind(1d0)), intent(out), allocatable :: L0_LEvec(:,:)
A complex square matrix that will hold the left eigenvectors of Liouvillian0.
complex(kind=kind(1d0)), intent(out), allocatable :: L0_REvec(:,:)
A complex square matrix that will hold the right eigenvectors of Liouvillian0.
Calls
Called by
Call graph
diagonalizelindblad_0 calls short_diag, zgemm
chargemigration calls diagonalizelindblad_0