LiouvillianPropagator – Charge Migration
LiouvillianPropagator Subroutine
84 statements
Source File
subroutine LiouvillianPropagator(L0_Eval, L0_LEvec, L0_REvec, zStatRho)
The central routine in simulating the dynamics of a quantum system subject to an external field, describing the time evolution of the system in Liouville space. Build the time-independent Lindblad superoperator
Where:
is the time derivative of the density matrix.
represents the commutator of the Hamiltonian and the density matrix , which is the standard von Neumann equation describing the unitary evolution of the system, the Liouvillian.
(L_{mn}) are the Lindblad (or jump) operators. These represent the different ways the environment can affect the system, leading to decoherence and relaxation.
The terms with describe the action of the environment on the system, and thus are responsible for transitions induced by the bath.
The terms with and subtract off double-counted terms and ensure the trace of the density matrix remains equal to 1. Behaving as "decoherence" processes where the system's off-diagonal elements (coherences) are diminished due to interactions with the environment.
For pure dephasing without relaxation:
For relaxation without pure dephasing: subject to the constraint where
Key steps in the subroutine:
Transform the initial density matrix zStatRho into Liouville space.
Propagate the transformed matrix in the absence of external fields for a time interval dt/2.
Convert the propagated matrix back into Hilbert space.
Consider the system's interaction with an external electric field by applying rotations in the Hilbert space.
Diagonalize the density matrix to determine the pure states it comprises.
Propagate each individual state under the influence of the external field.
Re-form the density matrix from the propagated pure states.
Repeat steps 1-3 for the re-formed density matrix to complete the propagation process over the time interval dt.
Notes:
This subroutine heavily relies on various matrix operations and makes use of other subroutines such as HilbertToLiouvilleMatrix, ZGEMV, LiouvilleToHilbertMatrix, DiagonalizeDipole, ZGEMM, Short_ZHEEV, and ExternalElectricFieldCart, which are not defined within this subroutine and are expected to be defined elsewhere.
Important to note is that certain variables used within this subroutine, such as dt, t, iSim, train, Z1, Zi, Z0, nStates, and Dmat, are not defined or passed as arguments, implying that they are either global variables or passed from a higher-level routine that calls this function.
The FIRST_CALL logical variable is used to execute certain lines of code only during the first invocation of the subroutine, primarily for the allocation and initialization of arrays.
This subroutine effectively encapsulates a single iteration or time step of the simulation. For a complete simulation over a given time period, this subroutine would typically be called repeatedly in a loop.
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1d0)), intent(in) :: L0_Eval(:)
a complex array holding the eigenvalues of the Liouville operator.
complex(kind=kind(1d0)), intent(in) :: L0_LEvec(:,:)
a complex array holding the left eigenvectors of the Liouville operator.
complex(kind=kind(1d0)), intent(in) :: L0_REvec(:,:)
a complex array holding the right eigenvectors of the Liouville operator.
complex(kind=kind(1d0)), intent(inout) :: zStatRho(:,:)
a complex array holding the initial state density matrix of the quantum system. The array is updated within the subroutine, and hence is an input/output parameter.
Calls
Called by
Call graph
liouvillianpropagator calls externalelectricfieldcart, diagonalizedipole, hilberttoliouvillematrix, liouvilletohilbertmatrix, short_zheev, zgemm, zgemv
diagonalizedipole calls short_diag
hilberttoliouvillematrix calls hilberttoliouvilleindexes
liouvilletohilbertmatrix calls hilberttoliouvilleindexes
chargemigration calls liouvillianpropagator