LoadOrbitals – Charge Migration
LoadOrbitals Subroutine
36 statements
Source File
public subroutine LoadOrbitals(Dir, number_of_orbitals, npts, OrbTab)
Uses
ModuleString
ModuleErrorHandling
Loads the Orbitals found inside the input_directory Loads the Orbitals from the grid_density.csv file inside the input_directory
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: Dir
integer, intent(in) :: number_of_orbitals
integer, intent(in) :: npts
real(kind=kind(1d0)), intent(out), allocatable :: OrbTab(:,:)
Calls
Called by
Call graph
loadorbitals calls assert, converttostrn, errormessage, stopexecution
chargemigration calls loadorbitals