name: docs
on:
  push:
    branches:
    - master

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        pip3 install sphinx-rtd-theme
        pip3 install click

    - name: Build docs
      run: |
        python -m Documentation.autodocumentation_python -p DensityPy -a "Ruben Fernandez Carbon" -s densitypy -d Documentation/pythondocs -e venv,Studies,old_files,densityfort,densitypy/frontend_tbd,frontend_tbd,Documentation/pythondocs -r
    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/pythondocs/build/html